[CmdletBinding()]
param (
    [string]$Version = "0.1.0",
    [string]$OutDir = "",
    [switch]$SkipTests
)

Set-StrictMode -Version Latest

$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
$rootDir = Resolve-Path (Join-Path $scriptDir "..")
$moduleDir = Join-Path $scriptDir "Azpe"
$standaloneFile = Join-Path $scriptDir "Invoke-AzpeProbe.ps1"
$distDir = if (-not [string]::IsNullOrEmpty($OutDir)) { $OutDir } else { $scriptDir }

Write-Host "Building AZPE PowerShell Compatibility Client v$Version..."

# 1. Deterministic Standalone Script Generation
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Auto-generated standalone script for AZPE PowerShell Compatibility Client v$Version")
[void]$sb.AppendLine("# DO NOT EDIT THIS FILE DIRECTLY. Edit module components in powershell/Azpe/")
[void]$sb.AppendLine(@"
[CmdletBinding()]
[Alias("azpe")]
param (
    [Parameter(Position = 0, Mandatory = `$false, ValueFromPipeline = `$true, ValueFromPipelineByPropertyName = `$true)]
    [string]`$Target = "",

    [Parameter(Mandatory = `$false)]
    [int]`$TimeoutSeconds = 5,

    [Parameter(Mandatory = `$false)]
    [switch]`$Detailed,

    [Parameter(Mandatory = `$false)]
    [switch]`$Json,

    [Parameter(Mandatory = `$false)]
    [switch]`$NoHttp,

    [Parameter(Mandatory = `$false)]
    [switch]`$NoColor
)
"@)
[void]$sb.AppendLine()

$privateFiles = Get-ChildItem -Path (Join-Path $moduleDir "Private") -Filter "*.ps1" | Sort-Object Name
foreach ($f in $privateFiles) {
    [void]$sb.AppendLine("# --- Begin $($f.Name) ---")
    $content = Get-Content -Path $f.FullName -Raw
    # Strip top-level Set-StrictMode calls to prevent duplicates
    $contentClean = $content -replace 'Set-StrictMode -Version Latest', '# Set-StrictMode'
    [void]$sb.AppendLine($contentClean)
    [void]$sb.AppendLine("# --- End $($f.Name) ---")
    [void]$sb.AppendLine()
}

$publicFiles = Get-ChildItem -Path (Join-Path $moduleDir "Public") -Filter "*.ps1" | Sort-Object Name
foreach ($f in $publicFiles) {
    [void]$sb.AppendLine("# --- Begin $($f.Name) ---")
    $content = Get-Content -Path $f.FullName -Raw
    $contentClean = $content -replace 'Set-StrictMode -Version Latest', '# Set-StrictMode'
    [void]$sb.AppendLine($contentClean)
    [void]$sb.AppendLine("# --- End $($f.Name) ---")
    [void]$sb.AppendLine()
}

# Add execution router for standalone execution
[void]$sb.AppendLine(@"
# Execution Router for Standalone Script
if (`$MyInvocation.InvocationName -ne '.') {
    `$evalResult = Invoke-AzpeProbe -Target `$Target -TimeoutSeconds `$TimeoutSeconds -Detailed:`$Detailed -Json:`$Json -NoHttp:`$NoHttp -NoColor:`$NoColor
    if (`$evalResult -and `$evalResult.ExitCode -ne `$null) {
        `$host.SetShouldExit(`$evalResult.ExitCode)
        [System.Environment]::ExitCode = `$evalResult.ExitCode
    }
}
"@)

[System.IO.File]::WriteAllText($standaloneFile, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "Generated standalone script: $standaloneFile"

# 2. Validate Module Manifest
if ((Get-Command Test-ModuleManifest -ErrorAction SilentlyContinue)) {
    $manifestPath = Join-Path $moduleDir "Azpe.psd1"
    $manifest = Test-ModuleManifest -Path $manifestPath -ErrorAction Stop
    Write-Host "Module Manifest validated successfully: $($manifest.Name) $($manifest.Version)"
}

# 3. Optional Pester Tests
if (-not $SkipTests) {
    $pester = Get-Module Pester -ListAvailable | Select-Object -First 1
    if ($pester) {
        Write-Host "Running Pester tests..."
        Import-Module Pester -Force
        $testResult = Invoke-Pester -Path (Join-Path $scriptDir "Tests") -PassThru
        if ($testResult.FailedCount -gt 0) {
            throw "$($testResult.FailedCount) Pester test(s) failed!"
        }
    } else {
        Write-Host "Pester not found. Skipping tests (pass -SkipTests to suppress this note)."
    }
}

# 4. Package Release ZIP
if (-not (Test-Path $distDir)) {
    New-Item -ItemType Directory -Path $distDir -Force | Out-Null
}

$zipPath = Join-Path $distDir "azpe-powershell_$Version.zip"
if (Test-Path $zipPath) {
    Remove-Item $zipPath -Force
}

$tempPkgDir = Join-Path $distDir "temp_pkg"
if (Test-Path $tempPkgDir) {
    Remove-Item $tempPkgDir -Recurse -Force
}

New-Item -ItemType Directory -Path $tempPkgDir -Force | Out-Null
Copy-Item -Path $moduleDir -Destination $tempPkgDir -Recurse -Force

Copy-Item -Path $standaloneFile -Destination (Join-Path $tempPkgDir "Invoke-AzpeProbe.ps1") -Force
Copy-Item -Path (Join-Path $scriptDir "README.md") -Destination (Join-Path $tempPkgDir "README.md") -ErrorAction SilentlyContinue
Copy-Item -Path (Join-Path $rootDir "LICENSE") -Destination (Join-Path $tempPkgDir "LICENSE") -ErrorAction SilentlyContinue

# Compress into zip archive
$zipSource = Join-Path $tempPkgDir "*"
Compress-Archive -Path $zipSource -DestinationPath $zipPath -Force
Remove-Item $tempPkgDir -Recurse -Force

Write-Host "Package created: $zipPath"

# Calculate SHA-256 checksum
if ((Get-Command Get-FileHash -ErrorAction SilentlyContinue)) {
    $hash = Get-FileHash -Path $zipPath -Algorithm SHA256
    Write-Host "SHA-256: $($hash.Hash)  azpe-powershell_$Version.zip"
}

Write-Host "Build complete!"
