# Auto-generated standalone script for AZPE PowerShell Compatibility Client v0.2.0-rc.1
# DO NOT EDIT THIS FILE DIRECTLY. Edit module components in powershell/Azpe/
[CmdletBinding()]
[Alias("azpe")]
param (
    [Parameter(Position = 0, Mandatory = $false, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
    [string]$Target = "",

    [Parameter(Mandatory = $false)]
    [int]$TimeoutSeconds = 5,

    [Parameter(Mandatory = $false)]
    [switch]$Detailed,

    [Parameter(Mandatory = $false)]
    [switch]$Json,

    [Parameter(Mandatory = $false)]
    [switch]$NoHttp,

    [Parameter(Mandatory = $false)]
    [switch]$NoColor
)

# --- Begin Assessment.ps1 ---
# Private/Assessment.ps1
# Assessment decision engine and evaluation logic for AZPE PowerShell Client

# Set-StrictMode

function Get-AzpeEvaluation {
    [CmdletBinding()]
    param (
        [PSCustomObject]$Target,
        [PSCustomObject]$DNSObs,
        [PSCustomObject]$AddrObs,
        [PSCustomObject]$TCPObs,
        [PSCustomObject]$TLSObs,
        [PSCustomObject]$HTTPObs,
        [switch]$NoHttp
    )

    $hostname = $Target.Hostname

    # 1. IP Literal Target
    if ($Target.TargetType -eq "IP_LITERAL") {
        $ex = "An IP address was provided instead of an Azure service hostname."
        $imp = "An IP address cannot test Private Endpoint DNS."
        $sum = "You entered an IP address:`n$hostname`n`n$imp`n`nUse the Azure service hostname configured in your application."
        return [PSCustomObject]@{
            Scenario    = "IP_LITERAL"
            ExitCode    = 8
            Title       = "The Azure service hostname is required"
            Explanation = $ex
            Impact      = $imp
            Summary     = $sum
            State       = "UNKNOWN"
            LikelyOwner = "UNKNOWN"
            NextAction  = "Use the Azure service hostname configured in your application."
            Warnings    = @()
        }
    }

    # 2. Unrecognized Non-Azure Target
    if ($Target.TargetType -eq "UNRECOGNIZED_TARGET") {
        $ex = "$hostname is not a recognized Azure Private Endpoint service hostname."
        $imp = "AZPE can only diagnose recognized Azure Private Endpoint targets."
        $sum = "$ex`n`nUse the Azure service hostname configured in your application, for example:`n  myvault.vault.azure.net`n  mystorage.blob.core.windows.net`n  mysearch.search.windows.net"
        return [PSCustomObject]@{
            Scenario    = "UNRECOGNIZED_TARGET"
            ExitCode    = 8
            Title       = "Cannot test this target"
            Explanation = $ex
            Impact      = $imp
            Summary     = $sum
            State       = "UNKNOWN"
            LikelyOwner = "UNKNOWN"
            NextAction  = "Use the Azure service hostname configured in your application."
            Warnings    = @()
        }
    }

    # 3. Possible Azure Service
    if ($Target.TargetType -eq "POSSIBLE_AZURE_SERVICE") {
        $ex = "AZPE's service catalogue does not recognize this specific Azure hostname pattern yet."
        $imp = "No Private Endpoint conclusion was made."
        $sum = "$hostname`n`n$imp`n`nYou can use -Detailed to view target information."
        return [PSCustomObject]@{
            Scenario    = "POSSIBLE_AZURE"
            ExitCode    = 8
            Title       = "This Azure service is not supported yet"
            Explanation = $ex
            Impact      = $imp
            Summary     = $sum
            State       = "UNKNOWN"
            LikelyOwner = "UNKNOWN"
            NextAction  = "You can use -Detailed to view target information."
            Warnings    = @()
        }
    }

    # 4. Recognized Azure Service - Evaluate DNS Results
    if ($DNSObs.status -in @("NOT_FOUND", "TIMEOUT", "TEMPORARY_FAILURE", "FAILURE")) {
        $ex = "The Azure service hostname could not be resolved."
        $imp = "DNS resolution failed from this execution environment."
        $sum = "$hostname`n`nWhat to do:`nRun this check inside the affected workload. If it still fails, send this result to your network or DNS team."
        return [PSCustomObject]@{
            Scenario    = "DNS_LOOKUP_FAILED"
            ExitCode    = 3
            Title       = "The Azure service name cannot be resolved"
            Explanation = $ex
            Impact      = $imp
            Summary     = $sum
            State       = "BROKEN"
            LikelyOwner = "DNS_OR_NETWORK"
            NextAction  = "Run this check inside the affected workload. If it still fails, send this result to your network or DNS team."
            Warnings    = @()
        }
    }

    switch ($AddrObs.classification) {
        "PRIVATE_ONLY" {
            # Evaluate TCP Connectivity
            if ($TCPObs -and $TCPObs.aggregateStatus -ne "NOT_ATTEMPTED") {
                switch ($TCPObs.aggregateStatus) {
                    "ALL_CONNECTED" {
                        # Evaluate TLS/HTTPS
                        if ($TLSObs -and $TLSObs.aggregateStatus -ne "NOT_ATTEMPTED") {
                            switch ($TLSObs.aggregateStatus) {
                                "ALL_VALID" {
                                    # Evaluate HTTP Probing
                                    if ($HTTPObs -and $HTTPObs.aggregateStatus -ne "NOT_ATTEMPTED") {
                                        switch ($HTTPObs.aggregateStatus) {
                                            "ALL_RESPONDED" {
                                                return Build-AzpeHttpRespondedEvaluation -Target $Target -Results $HTTPObs.results
                                            }
                                            "NONE_RESPONDED" {
                                                $lines = @()
                                                foreach ($r in $HTTPObs.results) {
                                                    $lines += "$hostname -> $($r.destination)"
                                                }
                                                $destBlock = $lines -join "`n"
                                                $ex = "The secure connection works, but no HTTP response was received before the timeout."
                                                $imp = "The HTTP request timed out waiting for headers from the Azure service."
                                                $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Valid`nAzure service   Response timed out`n`nThe secure connection works, but no HTTP response was received before the timeout.`n`nWhat to do:`nSend the detailed result to the application platform or service owner team."
                                                return [PSCustomObject]@{
                                                    Scenario    = "PRIVATE_HTTP_TIMEOUT"
                                                    ExitCode    = 7
                                                    Title       = "The Azure service did not respond in time"
                                                    Explanation = $ex
                                                    Impact      = $imp
                                                    Summary     = $sum
                                                    State       = "BROKEN"
                                                    LikelyOwner = "APPLICATION_OR_SERVICE"
                                                    NextAction  = "Send the detailed result to the application platform or service owner team."
                                                    Warnings    = @()
                                                }
                                            }
                                            "PARTIALLY_RESPONDED" {
                                                $lines = @()
                                                foreach ($r in $HTTPObs.results) {
                                                    if ($r.status -eq "RESPONDED") {
                                                        $lines += "$($r.destination.PadRight(18)) HTTP $($r.statusCode) $($r.statusText)"
                                                    } else {
                                                        $lines += "$($r.destination.PadRight(18)) HTTP probe failed"
                                                    }
                                                }
                                                $destBlock = $lines -join "`n"
                                                $ex = "At least one private address returned an HTTP response and at least one did not."
                                                $imp = "The application may behave failure-prone or intermittently depending on which address it uses."
                                                $sum = "$destBlock`n`nThe application may behave intermittently depending on which address it uses.`n`nWhat to do:`nSend the detailed result to your application platform or service owner team."
                                                return [PSCustomObject]@{
                                                    Scenario    = "PRIVATE_HTTP_PARTIAL"
                                                    ExitCode    = 8
                                                    Title       = "The Azure service responded on only some private addresses"
                                                    Explanation = $ex
                                                    Impact      = $imp
                                                    Summary     = $sum
                                                    State       = "UNKNOWN"
                                                    LikelyOwner = "APPLICATION_OR_SERVICE"
                                                    NextAction  = "Send the detailed result to your application platform or service owner team."
                                                    Warnings    = @()
                                                }
                                            }
                                        }
                                    }

                                    # TLS Valid fallback (when -NoHttp is used)
                                    $title = if ($TLSObs.results.Count -gt 1) { "Secure private connections look correct" } else { "Secure private connection looks correct" }
                                    $lines = @()
                                    foreach ($r in $TLSObs.results) {
                                        if ($TLSObs.results.Count -eq 1) {
                                            $lines += "$hostname -> $($r.destination)"
                                        } else {
                                            $lines += "$($r.destination.PadRight(18)) TLS valid"
                                        }
                                    }
                                    $destBlock = $lines -join "`n"
                                    $connStatusStr = if ($TLSObs.results.Count -gt 1) { "Working for all addresses" } else { "Working" }
                                    $tlsStatusStr = if ($TLSObs.results.Count -gt 1) { "Valid for all addresses" } else { "Valid" }
                                    $ex = "The Azure service hostname resolved privately, and this workload established a valid, trusted TLS connection to every private address."
                                    $imp = "DNS, TCP, and TLS validation look correct."
                                    $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      $connStatusStr`nTLS             $tlsStatusStr`nAzure service   Not tested`n`nHTTP probing was disabled with -NoHttp."
                                    return [PSCustomObject]@{
                                        Scenario    = "PRIVATE_TLS_VALID"
                                        ExitCode    = 0
                                        Title       = $title
                                        Explanation = $ex
                                        Impact      = $imp
                                        Summary     = $sum
                                        State       = "WORKING"
                                        LikelyOwner = "UNKNOWN"
                                        NextAction  = ""
                                        Warnings    = @()
                                    }
                                }

                                "NONE_VALID" {
                                    $lines = @()
                                    foreach ($r in $TLSObs.results) {
                                        $lines += "$hostname -> $($r.destination)"
                                    }
                                    $destBlock = $lines -join "`n"

                                    $domStatus = $TLSObs.results[0].status
                                    if ($domStatus -eq "HOSTNAME_MISMATCH") {
                                        $ex = "The private address is reachable, but it presented a certificate for a different hostname."
                                        $imp = "The application cannot establish a secure connection because certificate hostname validation failed."
                                        $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Hostname mismatch`n`nThe address is reachable, but it presented a certificate for a different hostname.`n`nWhat to do:`nSend the detailed result to your network security team."
                                        return [PSCustomObject]@{
                                            Scenario    = "PRIVATE_TLS_HOSTNAME_MISMATCH"
                                            ExitCode    = 6
                                            Title       = "The certificate does not match the Azure service name"
                                            Explanation = $ex
                                            Impact      = $imp
                                            Summary     = $sum
                                            State       = "BROKEN"
                                            LikelyOwner = "SECURITY_OR_PROXY"
                                            NextAction  = "Send the detailed result to your network security team."
                                            Warnings    = @()
                                        }
                                    } elseif ($domStatus -eq "UNTRUSTED_CERTIFICATE") {
                                        $ex = "The private address is reachable, but the certificate presented is not trusted by this workload."
                                        $imp = "The application cannot establish a secure connection because certificate trust validation failed."
                                        $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Certificate not trusted`n`nWhat to do:`nSend the detailed result to your application platform or network security team."
                                        return [PSCustomObject]@{
                                            Scenario    = "PRIVATE_TLS_UNTRUSTED"
                                            ExitCode    = 6
                                            Title       = "The certificate is not trusted by this workload"
                                            Explanation = $ex
                                            Impact      = $imp
                                            Summary     = $sum
                                            State       = "BROKEN"
                                            LikelyOwner = "SECURITY_OR_PROXY"
                                            NextAction  = "Send the detailed result to your application platform or network security team."
                                            Warnings    = @()
                                        }
                                    } else {
                                        $ex = "The private address is reachable, but TLS negotiation failed."
                                        $imp = "The application cannot establish a secure TLS connection."
                                        $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Failed`n`nThe private address is reachable, but TLS negotiation failed.`n`nWhat to do:`nSend the detailed result to your application platform or network security team."
                                        return [PSCustomObject]@{
                                            Scenario    = "PRIVATE_TLS_FAILED"
                                            ExitCode    = 6
                                            Title       = "The secure connection could not be established"
                                            Explanation = $ex
                                            Impact      = $imp
                                            Summary     = $sum
                                            State       = "BROKEN"
                                            LikelyOwner = "SECURITY_OR_PROXY"
                                            NextAction  = "Send the detailed result to your application platform or network security team."
                                            Warnings    = @()
                                        }
                                    }
                                }

                                "PARTIALLY_VALID" {
                                    $lines = @()
                                    foreach ($r in $TLSObs.results) {
                                        if ($r.status -eq "VALID") {
                                            $lines += "$($r.destination.PadRight(18)) TLS valid"
                                        } else {
                                            $lines += "$($r.destination.PadRight(18)) TLS failed"
                                        }
                                    }
                                    $destBlock = $lines -join "`n"
                                    $ex = "At least one private address validated TLS and at least one did not."
                                    $imp = "The application may behave differently depending on which address it uses."
                                    $sum = "$destBlock`n`nThe application may behave differently depending on which address it uses.`n`nWhat to do:`nSend the detailed result to your network security team."
                                    return [PSCustomObject]@{
                                        Scenario    = "PRIVATE_TLS_PARTIAL"
                                        ExitCode    = 8
                                        Title       = "TLS works for only some private addresses"
                                        Explanation = $ex
                                        Impact      = $imp
                                        Summary     = $sum
                                        State       = "UNKNOWN"
                                        LikelyOwner = "SECURITY_OR_PROXY"
                                        NextAction  = "Send the detailed result to your network security team."
                                        Warnings    = @()
                                    }
                                }
                            }
                        }
                    }

                    "NONE_CONNECTED" {
                        $title = if ($TCPObs.results.Count -gt 1) { "The private addresses cannot be reached" } else { "The private address cannot be reached" }
                        $lines = @()
                        foreach ($r in $TCPObs.results) {
                            if ($TCPObs.results.Count -eq 1) {
                                $failReason = if ($r.status -eq "TIMED_OUT") { "Timed out" } else { "Connection refused" }
                                $lines += "$hostname -> $($r.destination)`nResult: $failReason"
                            } else {
                                $lines += "$($r.destination.PadRight(18)) Connection failed"
                            }
                        }
                        $destBlock = $lines -join "`n"
                        $connStatusStr = if ($TCPObs.results.Count -gt 1) { "Failed for all addresses" } else { "Failed" }
                        $ex = "The Azure service hostname resolved privately, but this workload could not establish a TCP connection to the returned address."
                        $imp = "The application cannot currently connect to the Azure service on the requested port."
                        $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      $connStatusStr`n`nWhat to do:`nSend this result to your network team."
                        return [PSCustomObject]@{
                            Scenario    = "PRIVATE_TCP_UNREACHABLE"
                            ExitCode    = 5
                            Title       = $title
                            Explanation = $ex
                            Impact      = $imp
                            Summary     = $sum
                            State       = "BROKEN"
                            LikelyOwner = "NETWORK"
                            NextAction  = "Send this result to your network team."
                            Warnings    = @()
                        }
                    }

                    "PARTIALLY_CONNECTED" {
                        $lines = @()
                        foreach ($r in $TCPObs.results) {
                            if ($r.status -eq "CONNECTED") {
                                $lines += "$($r.destination.PadRight(18)) connected in $($r.durationMs) ms"
                            } else {
                                $lines += "$($r.destination.PadRight(18)) Connection failed"
                            }
                        }
                        $destBlock = $lines -join "`n"
                        $ex = "At least one returned private address accepted the TCP connection and at least one did not."
                        $imp = "The application may behave intermittently depending on which address it uses."
                        $sum = "$destBlock`n`nThe application may work intermittently depending on which address it uses.`n`nWhat to do:`nSend this result to your network team."
                        return [PSCustomObject]@{
                            Scenario    = "PRIVATE_TCP_PARTIAL"
                            ExitCode    = 8
                            Title       = "Some private addresses cannot be reached"
                            Explanation = $ex
                            Impact      = $imp
                            Summary     = $sum
                            State       = "UNKNOWN"
                            LikelyOwner = "NETWORK"
                            NextAction  = "Send this result to your network team."
                            Warnings    = @()
                        }
                    }
                }
            }

            # Phase 2 Private DNS fallback
            $lines = @()
            foreach ($a in $AddrObs.privateIps) {
                $lines += "$hostname -> $a (private)"
            }
            $destBlock = $lines -join "`n"
            $ex = "The service name points to a private address from this workload."
            $imp = "Connection not tested yet."
            $sum = "$destBlock`n`n$ex`n`n$imp"
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_DNS_ACTIVE"
                ExitCode    = 0
                Title       = "Private DNS looks correct"
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = "UNKNOWN"
                LikelyOwner = "UNKNOWN"
                NextAction  = ""
                Warnings    = @()
            }
        }

        "PUBLIC_ONLY" {
            $lines = @()
            foreach ($a in $AddrObs.publicIps) {
                $lines += "$hostname -> $a (public)"
            }
            $destBlock = $lines -join "`n"
            $ex = "The Azure service resolved to public addresses."
            $imp = "The application will attempt to use the public Azure endpoint."
            $sum = "$destBlock`n`n$imp`n`nWhat to do:`nIf you ran AZPE inside the affected workload, send this result to your network or DNS team."
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_DNS_NOT_ACTIVE"
                ExitCode    = 4
                Title       = "This workload is not using private DNS"
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = "NOT_PRIVATE"
                LikelyOwner = "DNS_OR_NETWORK"
                NextAction  = "If this test ran inside the affected workload, send this result to your network or DNS team."
                Warnings    = @()
            }
        }

        "MIXED_PRIVATE_PUBLIC" {
            $lines = @()
            foreach ($ipObs in $AddrObs.addresses) {
                $clsStr = if ($ipObs.classification -eq "PRIVATE") { "private" } else { "public" }
                $lines += "$hostname -> $($ipObs.address) ($clsStr)"
            }
            $destBlock = $lines -join "`n"
            $ex = "DNS returned a mixture of private and public IP addresses."
            $imp = "The application may use different network paths depending on which address it selects."
            $sum = "$destBlock`n`n$imp`n`nWhat to do:`nSend this result to your network or DNS team."
            return [PSCustomObject]@{
                Scenario    = "DNS_MIXED"
                ExitCode    = 8
                Title       = "DNS is returning both private and public addresses"
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = "UNKNOWN"
                LikelyOwner = "DNS_OR_NETWORK"
                NextAction  = "Send this result to your network or DNS team."
                Warnings    = @("DNS returned a mixture of private and public IP addresses.")
            }
        }

        "SPECIAL_ONLY" {
            $ex = "DNS returned special-purpose IP addresses."
            $imp = "This result cannot be used to evaluate Azure Private Endpoint connectivity."
            $sum = "$hostname`n`n$imp`n`nWhat to do:`nSend the detailed result to your network or DNS team."
            return [PSCustomObject]@{
                Scenario    = "SPECIAL_ONLY"
                ExitCode    = 8
                Title       = "DNS returned an unexpected address"
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = "UNKNOWN"
                LikelyOwner = "DNS_OR_NETWORK"
                NextAction  = "Send the detailed result to your network or DNS team."
                Warnings    = @()
            }
        }

        default {
            $ex = "DNS returned an ambiguous response."
            $imp = "This result cannot be used to evaluate Azure Private Endpoint connectivity."
            $sum = "$hostname`n`nWhat to do:`nSend this result to your network or DNS team."
            return [PSCustomObject]@{
                Scenario    = "DNS_MIXED"
                ExitCode    = 8
                Title       = "DNS result is inconclusive"
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = "UNKNOWN"
                LikelyOwner = "DNS_OR_NETWORK"
                NextAction  = "Send this result to your network or DNS team."
                Warnings    = @()
            }
        }
    }
}

function Build-AzpeHttpRespondedEvaluation {
    [CmdletBinding()]
    param (
        [PSCustomObject]$Target,
        [PSCustomObject[]]$Results
    )

    $hostname = $Target.Hostname
    $res = $Results[0]
    $cat = $res.responseCategory

    $lines = @()
    foreach ($r in $Results) {
        $lines += "$hostname -> $($r.destination)`nHTTP $($r.statusCode) $($r.statusText)"
    }
    $destBlock = $lines -join "`n`n"

    $title = "The Azure service responded"
    $state = "WORKING"

    switch ($cat) {
        "SUCCESS" {
            $serviceLine = "Responded successfully"
            $ex = "The private network and HTTPS path look correct. The Azure service returned a successful response."
            $imp = "End-to-end network and HTTPS transport are working."
            $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Valid`nAzure service   $serviceLine`n`nThe private network and HTTPS path look correct."
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_HTTP_RESPONDED"
                ExitCode    = 0
                Title       = $title
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = $state
                LikelyOwner = "UNKNOWN"
                NextAction  = ""
                Warnings    = @()
            }
        }

        "AUTHENTICATION_REQUIRED" {
            $serviceLine = "Authentication required"
            $ex = "The private connection is working. The Azure service responded and requires authentication."
            $imp = "Network and HTTPS transport are working. The application may be missing or sending invalid credentials."
            $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Valid`nAzure service   $serviceLine`n`nThe private connection is working. The service requires authentication.`n`nWhat to do:`nIf the application still fails, check how it obtains and sends its Azure credentials."
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_HTTP_AUTH_REQUIRED"
                ExitCode    = 0
                Title       = $title
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = $state
                LikelyOwner = "APPLICATION_OR_IDENTITY"
                NextAction  = "If the application still fails, check how it obtains and sends its Azure credentials."
                Warnings    = @()
            }
        }

        "ACCESS_DENIED" {
            $serviceLine = "Access denied"
            $ex = "The private connection is working. The Azure service denied this unauthenticated request."
            $imp = "Network and HTTPS transport are working. The application may require an authorized identity or RBAC role."
            $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Valid`nAzure service   $serviceLine`n`nThe private connection is working. The service denied this unauthenticated request.`n`nWhat to do:`nIf the application still fails, check its identity and Azure permissions."
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_HTTP_ACCESS_DENIED"
                ExitCode    = 0
                Title       = $title
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = $state
                LikelyOwner = "APPLICATION_OR_IDENTITY"
                NextAction  = "If the application still fails, check its identity and Azure permissions."
                Warnings    = @()
            }
        }

        "NOT_FOUND" {
            $serviceLine = "Requested path not found"
            $ex = "The private connection is working. The Azure service responded that the requested path was not found."
            $imp = "Network and HTTPS transport are working."
            $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Valid`nAzure service   $serviceLine`n`nThe private connection is working. The requested path was not found."
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_HTTP_NOT_FOUND"
                ExitCode    = 0
                Title       = $title
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = $state
                LikelyOwner = "APPLICATION"
                NextAction  = ""
                Warnings    = @()
            }
        }

        "THROTTLED" {
            $serviceLine = "Request throttled"
            $ex = "The private connection is working. The Azure service is currently throttling requests."
            $imp = "Network and HTTPS transport are working. Service rate limits are active."
            $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Valid`nAzure service   $serviceLine`n`nThe private connection is working. The service is currently throttling requests.`n`nWhat to do:`nCheck the application retry behavior and service limits."
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_HTTP_THROTTLED"
                ExitCode    = 0
                Title       = $title
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = $state
                LikelyOwner = "APPLICATION_OR_SERVICE"
                NextAction  = "Check the application retry behavior and service limits."
                Warnings    = @()
            }
        }

        default {
            $serviceLine = "Responded (HTTP $($res.statusCode))"
            $ex = "The private connection is working. The Azure service returned an HTTP response."
            $imp = "Network and HTTPS transport are working."
            $sum = "$destBlock`n`nPrivate DNS     Looks correct`nConnection      Working`nTLS             Valid`nAzure service   $serviceLine`n`nThe private connection is working."
            return [PSCustomObject]@{
                Scenario    = "PRIVATE_HTTP_RESPONDED"
                ExitCode    = 0
                Title       = $title
                Explanation = $ex
                Impact      = $imp
                Summary     = $sum
                State       = $state
                LikelyOwner = "APPLICATION_OR_SERVICE"
                NextAction  = ""
                Warnings    = @()
            }
        }
    }
}

# --- End Assessment.ps1 ---

# --- Begin Capability.ps1 ---
# Private/Capability.ps1
# Environment and capability detection for AZPE PowerShell Client

# Set-StrictMode

function Get-AzpeCapability {
    [CmdletBinding()]
    param ()

    $psVer = "Unknown"
    if ($PSVersionTable -and $PSVersionTable.PSVersion) {
        $psVer = $PSVersionTable.PSVersion.ToString()
    }

    $editionVal = "Unknown"
    if ($PSVersionTable -and $PSVersionTable.PSEdition) {
        $editionVal = $PSVersionTable.PSEdition
    }

    $langMode = "FullLanguage"
    if ($ExecutionContext -and $ExecutionContext.SessionState -and $ExecutionContext.SessionState.LanguageMode) {
        $langMode = $ExecutionContext.SessionState.LanguageMode.ToString()
    }

    $hasResolveDns = ($null -ne (Get-Command Resolve-DnsName -ErrorAction SilentlyContinue))
    $hasTestNetConn = ($null -ne (Get-Command Test-NetConnection -ErrorAction SilentlyContinue))

    # Locate native curl.exe executable (must be Application command type, not alias)
    $curlCmd = Get-Command curl.exe -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
    $hasCurl = ($null -ne $curlCmd)
    $curlPath = ""
    $curlVer = ""

    if ($hasCurl) {
        $curlPath = $curlCmd.Source
        try {
            # Bounded output from curl.exe --version
            $verOutput = & $curlCmd.Source --version 2>&1
            if ($verOutput) {
                $firstLine = $verOutput[0]
                if ($firstLine -match 'curl\s+([0-9]+\.[0-9]+\.[0-9]+)') {
                    $curlVer = $Matches[1]
                } else {
                    $curlVer = $firstLine
                }
            }
        } catch {
            $curlVer = "Unknown"
        }
    }

    $hasConvertToJson = ($null -ne (Get-Command ConvertTo-Json -ErrorAction SilentlyContinue))

    $dnsMethod = "UNAVAILABLE"
    if ($hasResolveDns) {
        $dnsMethod = "RESOLVE_DNS_NAME"
    } else {
        # Check if .NET DNS is available
        try {
            [void][System.Net.Dns]
            $dnsMethod = "DOTNET_DNS"
        } catch {
            $dnsMethod = "UNAVAILABLE"
        }
    }

    $tcpMethod = "UNAVAILABLE"
    if ($hasTestNetConn) {
        $tcpMethod = "TEST_NET_CONNECTION"
    } else {
        try {
            [void][System.Net.Sockets.TcpClient]
            $tcpMethod = "SOCKETS_TCP_CLIENT"
        } catch {
            $tcpMethod = "UNAVAILABLE"
        }
    }

    $tlsHttpMethod = "UNAVAILABLE"
    if ($hasCurl) {
        $tlsHttpMethod = "CURL_EXE_RESOLVE"
    }

    return [PSCustomObject]@{
        EngineName        = "POWERSHELL_COMPAT"
        EngineVersion     = "0.2.0-rc.1"
        PowerShellVersion = $psVer
        PowerShellEdition = $editionVal
        LanguageMode      = $langMode
        HasResolveDnsName = $hasResolveDns
        HasTestNetConnection = $hasTestNetConn
        HasCurl           = $hasCurl
        CurlPath          = $curlPath
        CurlVersion       = $curlVer
        HasConvertToJson  = $hasConvertToJson
        DnsMethod         = $dnsMethod
        TcpMethod         = $tcpMethod
        TlsHttpMethod     = $tlsHttpMethod
    }
}

# --- End Capability.ps1 ---

# --- Begin Catalogue.ps1 ---
# Private/Catalogue.ps1
# Azure target recognition rules and boundary-safe suffix catalogue for AZPE PowerShell Client

# Set-StrictMode

function Get-AzpeServiceCatalogue {
    [CmdletBinding()]
    param ()

    $patterns = @(
        [PSCustomObject]@{ Suffix = ".vault.azure.net"; Family = "KEY_VAULT"; DisplayName = "Key Vault" }
        [PSCustomObject]@{ Suffix = ".managedhsm.azure.net"; Family = "KEY_VAULT"; DisplayName = "Key Vault" }
        [PSCustomObject]@{ Suffix = ".blob.core.windows.net"; Family = "STORAGE_BLOB"; DisplayName = "Storage (Blob)" }
        [PSCustomObject]@{ Suffix = ".dfs.core.windows.net"; Family = "STORAGE_DFS"; DisplayName = "Storage (Data Lake Gen2 / DFS)" }
        [PSCustomObject]@{ Suffix = ".file.core.windows.net"; Family = "STORAGE_FILE"; DisplayName = "Storage (File)" }
        [PSCustomObject]@{ Suffix = ".queue.core.windows.net"; Family = "STORAGE_QUEUE"; DisplayName = "Storage (Queue)" }
        [PSCustomObject]@{ Suffix = ".table.core.windows.net"; Family = "STORAGE_TABLE"; DisplayName = "Storage (Table)" }
        [PSCustomObject]@{ Suffix = ".web.core.windows.net"; Family = "STORAGE_WEB"; DisplayName = "Storage (Static Web)" }
        [PSCustomObject]@{ Suffix = ".search.windows.net"; Family = "AI_SEARCH"; DisplayName = "Azure AI Search" }
        [PSCustomObject]@{ Suffix = ".database.windows.net"; Family = "SQL"; DisplayName = "Azure SQL Database" }
        [PSCustomObject]@{ Suffix = ".documents.azure.com"; Family = "COSMOS_DB"; DisplayName = "Azure Cosmos DB" }
        [PSCustomObject]@{ Suffix = ".mongo.cosmos.azure.com"; Family = "COSMOS_DB"; DisplayName = "Azure Cosmos DB" }
        [PSCustomObject]@{ Suffix = ".cassandra.cosmos.azure.com"; Family = "COSMOS_DB"; DisplayName = "Azure Cosmos DB" }
        [PSCustomObject]@{ Suffix = ".gremlin.cosmos.azure.com"; Family = "COSMOS_DB"; DisplayName = "Azure Cosmos DB" }
        [PSCustomObject]@{ Suffix = ".table.cosmos.azure.com"; Family = "COSMOS_DB"; DisplayName = "Azure Cosmos DB" }
        [PSCustomObject]@{ Suffix = ".openai.azure.com"; Family = "AZURE_OPENAI"; DisplayName = "Azure OpenAI" }
        [PSCustomObject]@{ Suffix = ".azurecr.io"; Family = "CONTAINER_REGISTRY"; DisplayName = "Azure Container Registry" }
        [PSCustomObject]@{ Suffix = ".azconfig.io"; Family = "APP_CONFIGURATION"; DisplayName = "Azure App Configuration" }
        [PSCustomObject]@{ Suffix = ".servicebus.windows.net"; Family = "SERVICE_BUS"; DisplayName = "Azure Service Bus / Event Hubs" }
        [PSCustomObject]@{ Suffix = ".redis.cache.windows.net"; Family = "REDIS_CACHE"; DisplayName = "Azure Cache for Redis" }
        [PSCustomObject]@{ Suffix = ".eventgrid.azure.net"; Family = "EVENT_GRID"; DisplayName = "Azure Event Grid" }
        [PSCustomObject]@{ Suffix = ".service.signalr.net"; Family = "SIGNALR"; DisplayName = "Azure SignalR Service" }
        [PSCustomObject]@{ Suffix = ".datafactory.azure.net"; Family = "DATA_FACTORY"; DisplayName = "Azure Data Factory" }
        [PSCustomObject]@{ Suffix = ".dev.azuresynapse.net"; Family = "SYNAPSE"; DisplayName = "Azure Synapse Analytics" }
        [PSCustomObject]@{ Suffix = ".sql.azuresynapse.net"; Family = "SYNAPSE"; DisplayName = "Azure Synapse SQL" }
        [PSCustomObject]@{ Suffix = ".azure-automation.net"; Family = "AUTOMATION"; DisplayName = "Azure Automation" }
    )

    $possibleDomains = @(
        ".azure.com",
        ".azure.net",
        ".windows.net",
        ".azurecr.io",
        ".azconfig.io",
        ".cloudapp.azure.com",
        ".azurewebsites.net",
        ".azure-api.net",
        ".azmk8s.io"
    )

    return [PSCustomObject]@{
        RecognizedPatterns   = $patterns
        PossibleAzureDomains = $possibleDomains
    }
}

function Get-AzpeFamilyDisplayName {
    [CmdletBinding()]
    param (
        [string]$Family
    )

    switch ($Family) {
        "KEY_VAULT"          { return "Key Vault" }
        "STORAGE_BLOB"       { return "Storage (Blob)" }
        "STORAGE_DFS"        { return "Storage (Data Lake Gen2 / DFS)" }
        "STORAGE_FILE"       { return "Storage (File)" }
        "STORAGE_QUEUE"      { return "Storage (Queue)" }
        "STORAGE_TABLE"      { return "Storage (Table)" }
        "STORAGE_WEB"        { return "Storage (Static Web)" }
        "AI_SEARCH"          { return "Azure AI Search" }
        "SQL"                { return "Azure SQL Database" }
        "COSMOS_DB"          { return "Azure Cosmos DB" }
        "AZURE_OPENAI"       { return "Azure OpenAI" }
        "CONTAINER_REGISTRY" { return "Azure Container Registry" }
        "APP_CONFIGURATION"  { return "Azure App Configuration" }
        "SERVICE_BUS"        { return "Azure Service Bus / Event Hubs" }
        "REDIS_CACHE"        { return "Azure Cache for Redis" }
        "EVENT_GRID"         { return "Azure Event Grid" }
        "SIGNALR"            { return "Azure SignalR Service" }
        "DATA_FACTORY"       { return "Azure Data Factory" }
        "SYNAPSE"            { return "Azure Synapse Analytics" }
        "AUTOMATION"         { return "Azure Automation" }
        "OTHER_AZURE"        { return "Azure Service" }
        default              { return "Unknown Service" }
    }
}

function Classify-AzpeTarget {
    [CmdletBinding()]
    param (
        [string]$Hostname
    )

    $cleanHost = $Hostname.ToLower().TrimEnd('.')

    # Check if host is an IP literal
    [System.Net.IPAddress]$parsedIp = $null
    if ([System.Net.IPAddress]::TryParse($cleanHost, [ref]$parsedIp)) {
        return [PSCustomObject]@{
            TargetType         = "IP_LITERAL"
            AzureServiceFamily = "NONE"
        }
    }

    $cat = Get-AzpeServiceCatalogue

    # Boundary-safe recognized pattern check
    foreach ($p in $cat.RecognizedPatterns) {
        if ($cleanHost.EndsWith($p.Suffix)) {
            $prefix = $cleanHost.Substring(0, $cleanHost.Length - $p.Suffix.Length)
            if ($prefix.Length -gt 0 -and -not $prefix.Contains('/')) {
                return [PSCustomObject]@{
                    TargetType         = "RECOGNIZED_AZURE_SERVICE"
                    AzureServiceFamily = $p.Family
                }
            }
        }
    }

    # Possible Azure generic domain check
    foreach ($domain in $cat.PossibleAzureDomains) {
        if ($cleanHost.EndsWith($domain)) {
            $prefix = $cleanHost.Substring(0, $cleanHost.Length - $domain.Length)
            if ($prefix.Length -gt 0) {
                return [PSCustomObject]@{
                    TargetType         = "POSSIBLE_AZURE_SERVICE"
                    AzureServiceFamily = "OTHER_AZURE"
                }
            }
        }
    }

    return [PSCustomObject]@{
        TargetType         = "UNRECOGNIZED_TARGET"
        AzureServiceFamily = "NONE"
    }
}

# --- End Catalogue.ps1 ---

# --- Begin Curl.ps1 ---
# Private/Curl.ps1
# Windows curl.exe discovery, direct-IP --resolve execution, and HTTP response parsing for AZPE PowerShell Client

# Set-StrictMode

function Invoke-AzpeCurlHttpsProbe {
    [CmdletBinding()]
    param (
        [string]$Hostname,
        [int]$Port = 443,
        [string]$Scheme = "https",
        [string]$PathAndQuery = "/",
        [string[]]$ConnectedIPs,
        [PSCustomObject]$Capability,
        [int]$TimeoutSeconds = 5,
        [switch]$NoHttp
    )

    if ($null -eq $ConnectedIPs -or $ConnectedIPs.Count -eq 0 -or -not $Capability.HasCurl) {
        return [PSCustomObject]@{
            TLSObservation  = [PSCustomObject]@{
                status          = "SKIPPED"
                aggregateStatus = "NOT_ATTEMPTED"
                serverName      = $Hostname
                durationMs      = 0
                results         = @()
                note            = "TLS probe not performed"
            }
            HTTPObservation = [PSCustomObject]@{
                status          = "SKIPPED"
                aggregateStatus = "NOT_ATTEMPTED"
                method          = "GET"
                path            = $PathAndQuery
                durationMs      = 0
                results         = @()
                note            = "HTTP probe not performed"
            }
        }
    }

    $swTotal = [System.Diagnostics.Stopwatch]::StartNew()

    $tlsResults = [System.Collections.Generic.List[PSCustomObject]]::new()
    $httpResults = [System.Collections.Generic.List[PSCustomObject]]::new()

    $tlsValidCount = 0
    $tlsFailedCount = 0

    $httpRespondedCount = 0
    $httpFailedCount = 0

    # Determine null device path (NUL on Windows, /dev/null on Unix)
    $nullDevice = if ([System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT) { "NUL" } else { "/dev/null" }

    $targetUrl = "$Scheme`://$Hostname`:$Port$PathAndQuery"
    $redactedPath = Redact-AzpeQueryValues -PathAndQuery $PathAndQuery

    foreach ($ip in $ConnectedIPs) {
        # Format destination and resolve string
        $dest = if ($ip.Contains(':')) { "[$ip]:$Port" } else { "$ip`:$Port" }
        $resolveEntry = if ($ip.Contains(':')) { "${Hostname}:${Port}:[$ip]" } else { "${Hostname}:${Port}:${ip}" }

        # Construct curl argument array (No shell command string concatenation!)
        $curlArgs = @(
            "--silent",
            "--show-error",
            "--output", $nullDevice,
            "--write-out", "%{http_code}\n%{time_total}\n%{remote_ip}\n%{ssl_verify_result}",
            "--connect-timeout", $TimeoutSeconds.ToString(),
            "--max-time", $TimeoutSeconds.ToString(),
            "--noproxy", "*",
            "--max-redirs", "0",
            "--resolve", $resolveEntry,
            "--",
            $targetUrl
        )

        $swIp = [System.Diagnostics.Stopwatch]::StartNew()

        $curlExitCode = -1
        $curlStdout = ""
        $curlStderr = ""

        try {
            # Execute curl.exe directly using array arguments
            $pinfo = [System.Diagnostics.ProcessStartInfo]::new()
            $pinfo.FileName = $Capability.CurlPath
            $pinfo.UseShellExecute = $false
            $pinfo.RedirectStandardOutput = $true
            $pinfo.RedirectStandardError = $true
            $pinfo.CreateNoWindow = $true

            foreach ($arg in $curlArgs) {
                $pinfo.ArgumentList.Add($arg)
            }

            $proc = [System.Diagnostics.Process]::Start($pinfo)
            $curlStdout = $proc.StandardOutput.ReadToEnd()
            $curlStderr = $proc.StandardError.ReadToEnd()
            $proc.WaitForExit()
            $curlExitCode = $proc.ExitCode
        } catch {
            $curlExitCode = 99
            $curlStderr = $_.Exception.Message
        }

        $swIp.Stop()

        # Parse curl stdout write-out format
        $httpCode = 0
        $timeTotalSec = 0.0
        $remoteIp = ""
        $sslVerifyResult = -1

        if (-not [string]::IsNullOrEmpty($curlStdout)) {
            $lines = $curlStdout.Trim().Split("`n")
            if ($lines.Count -ge 1) { [int]::TryParse($lines[0].Trim(), [ref]$httpCode) | Out-Null }
            if ($lines.Count -ge 2) { [double]::TryParse($lines[1].Trim(), [ref]$timeTotalSec) | Out-Null }
            if ($lines.Count -ge 3) { $remoteIp = $lines[2].Trim() }
            if ($lines.Count -ge 4) { [int]::TryParse($lines[3].Trim(), [ref]$sslVerifyResult) | Out-Null }
        }

        # Classify TLS and HTTP observation for this address
        $tlsStatusStr = "ERROR"
        $tlsErrCat = ""
        $tlsErrMsg = ""
        $bTrue = $true
        $bFalse = $false

        $httpStatusStr = "ERROR"
        $httpErrCat = ""
        $httpErrMsg = ""

        if ($curlExitCode -eq 0 -or $httpCode -gt 0) {
            # TLS handshake succeeded
            $tlsStatusStr = "VALID"
            $tlsValidCount++

            # HTTP response received
            $httpStatusStr = "RESPONDED"
            $httpRespondedCount++

            $statusText = Get-AzpeHttpStatusText -Code $httpCode
            $cat = Categorize-AzpeHttpStatusCode -Code $httpCode

            $httpResults.Add([PSCustomObject]@{
                address          = $ip
                destination      = $dest
                serverName       = $Hostname
                host             = $Hostname
                method           = "GET"
                requestUri       = $redactedPath
                status           = "RESPONDED"
                statusCode       = $httpCode
                statusText       = $statusText
                responseCategory = $cat
                durationMs       = $swIp.ElapsedMilliseconds
                redirectFollowed = $false
            })

            $tlsResults.Add([PSCustomObject]@{
                address            = $ip
                destination        = $dest
                port               = $Port
                serverName         = $Hostname
                status             = "VALID"
                hostnameValid      = $true
                certificateTrusted = $true
                durationMs         = $swIp.ElapsedMilliseconds
            })
        } else {
            # Categorize curl exit errors
            $tlsFailedCount++
            $httpFailedCount++

            $errStr = $curlStderr.Trim()

            switch ($curlExitCode) {
                28 { # Timeout
                    $tlsStatusStr = "HANDSHAKE_TIMEOUT"
                    $tlsErrCat = "TIMEOUT"
                    $tlsErrMsg = "TLS handshake timed out"

                    $httpStatusStr = "TIMEOUT"
                    $httpErrCat = "TIMEOUT"
                    $httpErrMsg = "HTTP request timed out"
                }
                35 { # Handshake failed
                    $tlsStatusStr = "HANDSHAKE_FAILED"
                    $tlsErrCat = "HANDSHAKE_FAILED"
                    $tlsErrMsg = if ($errStr) { $errStr } else { "TLS handshake failed" }

                    $httpStatusStr = "TLS_FAILED"
                    $httpErrCat = "HANDSHAKE_FAILED"
                    $httpErrMsg = $tlsErrMsg
                }
                51 { # Hostname mismatch
                    $tlsStatusStr = "HOSTNAME_MISMATCH"
                    $tlsErrCat = "HOSTNAME_MISMATCH"
                    $tlsErrMsg = "TLS certificate hostname mismatch"

                    $httpStatusStr = "TLS_FAILED"
                    $httpErrCat = "HOSTNAME_MISMATCH"
                    $httpErrMsg = $tlsErrMsg
                }
                60 { # Peer certificate cannot be authenticated (untrusted)
                    $tlsStatusStr = "UNTRUSTED_CERTIFICATE"
                    $tlsErrCat = "UNTRUSTED_CERTIFICATE"
                    $tlsErrMsg = "Certificate is not trusted by system trust store"

                    $httpStatusStr = "TLS_FAILED"
                    $httpErrCat = "UNTRUSTED_CERTIFICATE"
                    $httpErrMsg = $tlsErrMsg
                }
                default {
                    if ($errStr -match 'certificate' -or $errStr -match 'SSL' -or $errStr -match 'TLS') {
                        if ($errStr -match 'match') {
                            $tlsStatusStr = "HOSTNAME_MISMATCH"
                            $tlsErrCat = "HOSTNAME_MISMATCH"
                        } elseif ($errStr -match 'expire') {
                            $tlsStatusStr = "EXPIRED_CERTIFICATE"
                            $tlsErrCat = "EXPIRED_CERTIFICATE"
                        } else {
                            $tlsStatusStr = "UNTRUSTED_CERTIFICATE"
                            $tlsErrCat = "UNTRUSTED_CERTIFICATE"
                        }
                        $tlsErrMsg = $errStr
                        $httpStatusStr = "TLS_FAILED"
                        $httpErrCat = $tlsErrCat
                        $httpErrMsg = $tlsErrMsg
                    } else {
                        $tlsStatusStr = "HANDSHAKE_FAILED"
                        $tlsErrCat = "HANDSHAKE_FAILED"
                        $tlsErrMsg = if ($errStr) { $errStr } else { "TLS handshake failed" }

                        $httpStatusStr = "CONNECTION_FAILED"
                        $httpErrCat = "CONNECTION_FAILED"
                        $httpErrMsg = $tlsErrMsg
                    }
                }
            }

            $tlsResults.Add([PSCustomObject]@{
                address       = $ip
                destination   = $dest
                port          = $Port
                serverName    = $Hostname
                status        = $tlsStatusStr
                durationMs    = $swIp.ElapsedMilliseconds
                errorCategory = $tlsErrCat
                errorMessage  = $tlsErrMsg
            })

            $httpResults.Add([PSCustomObject]@{
                address       = $ip
                destination   = $dest
                serverName    = $Hostname
                host          = $Hostname
                method        = "GET"
                requestUri    = $redactedPath
                status        = $httpStatusStr
                durationMs    = $swIp.ElapsedMilliseconds
                errorCategory = $httpErrCat
                errorMessage  = $httpErrMsg
            })
        }
    }

    $swTotal.Stop()

    # Aggregate TLS status
    $aggTlsStatus = "NONE_VALID"
    $topTlsStatus = "FAILED"
    if ($tlsValidCount -eq $ConnectedIPs.Count) {
        $aggTlsStatus = "ALL_VALID"
        $topTlsStatus = "SUCCESS"
    } elseif ($tlsValidCount -gt 0 -and $tlsFailedCount -gt 0) {
        $aggTlsStatus = "PARTIALLY_VALID"
        $topTlsStatus = "PARTIAL"
    }

    # Aggregate HTTP status
    $aggHttpStatus = "NONE_RESPONDED"
    $topHttpStatus = "FAILED"
    if ($httpRespondedCount -eq $ConnectedIPs.Count) {
        $aggHttpStatus = "ALL_RESPONDED"
        $topHttpStatus = "SUCCESS"
    } elseif ($httpRespondedCount -gt 0 -and $httpFailedCount -gt 0) {
        $aggHttpStatus = "PARTIALLY_RESPONDED"
        $topHttpStatus = "PARTIAL"
    }

    if ($NoHttp) {
        $httpObs = [PSCustomObject]@{
            status          = "SKIPPED"
            aggregateStatus = "NOT_ATTEMPTED"
            method          = "GET"
            path            = $redactedPath
            durationMs      = 0
            results         = @()
            note            = "HTTP probing was disabled with -NoHttp"
        }
    } else {
        $httpObs = [PSCustomObject]@{
            status          = $topHttpStatus
            aggregateStatus = $aggHttpStatus
            method          = "GET"
            path            = $redactedPath
            durationMs      = $swTotal.ElapsedMilliseconds
            results         = $httpResults.ToArray()
        }
    }

    $tlsObs = [PSCustomObject]@{
        status          = $topTlsStatus
        aggregateStatus = $aggTlsStatus
        serverName      = $Hostname
        durationMs      = $swTotal.ElapsedMilliseconds
        results         = $tlsResults.ToArray()
    }

    return [PSCustomObject]@{
        TLSObservation  = $tlsObs
        HTTPObservation = $httpObs
    }
}

function Categorize-AzpeHttpStatusCode {
    [CmdletBinding()]
    param (
        [int]$Code
    )

    if ($Code -eq 200 -or ($Code -ge 201 -and $Code -le 299)) {
        return "SUCCESS"
    }
    if ($Code -eq 401) {
        return "AUTHENTICATION_REQUIRED"
    }
    if ($Code -eq 403) {
        return "ACCESS_DENIED"
    }
    if ($Code -eq 404) {
        return "NOT_FOUND"
    }
    if ($Code -eq 405) {
        return "METHOD_NOT_ALLOWED"
    }
    if ($Code -eq 409) {
        return "CONFLICT"
    }
    if ($Code -eq 429) {
        return "THROTTLED"
    }
    if ($Code -ge 500 -and $Code -le 599) {
        return "SERVER_ERROR"
    }
    if ($Code -ge 300 -and $Code -le 399) {
        return "REDIRECTION"
    }
    if ($Code -ge 400 -and $Code -le 499) {
        return "CLIENT_ERROR"
    }

    return "OTHER_RESPONSE"
}

function Get-AzpeHttpStatusText {
    [CmdletBinding()]
    param (
        [int]$Code
    )

    switch ($Code) {
        200 { return "OK" }
        201 { return "Created" }
        202 { return "Accepted" }
        204 { return "No Content" }
        301 { return "Moved Permanently" }
        302 { return "Found" }
        307 { return "Temporary Redirect" }
        308 { return "Permanent Redirect" }
        400 { return "Bad Request" }
        401 { return "Unauthorized" }
        403 { return "Forbidden" }
        404 { return "Not Found" }
        405 { return "Method Not Allowed" }
        409 { return "Conflict" }
        429 { return "Too Many Requests" }
        500 { return "Internal Server Error" }
        502 { return "Bad Gateway" }
        503 { return "Service Unavailable" }
        504 { return "Gateway Timeout" }
        default { return "HTTP $Code" }
    }
}

# --- End Curl.ps1 ---

# --- Begin Dns.ps1 ---
# Private/Dns.ps1
# Operating system DNS resolution and IP address classification for AZPE PowerShell Client

# Set-StrictMode

function Classify-AzpeIpAddress {
    [CmdletBinding()]
    param (
        [System.Net.IPAddress]$IP
    )

    if ($null -eq $IP) {
        return "UNKNOWN"
    }

    $bytes = $IP.GetAddressBytes()

    if ($IP.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetwork) {
        $b0 = [int]$bytes[0]
        $b1 = [int]$bytes[1]
        $b2 = [int]$bytes[2]

        # UNSPECIFIED: 0.0.0.0
        if ($b0 -eq 0 -and $b1 -eq 0 -and $b2 -eq 0 -and $bytes[3] -eq 0) {
            return "UNSPECIFIED"
        }

        # LOOPBACK: 127.0.0.0/8
        if ($b0 -eq 127) {
            return "LOOPBACK"
        }

        # MULTICAST: 224.0.0.0/4 (224-239)
        if ($b0 -ge 224 -and $b0 -le 239) {
            return "MULTICAST"
        }

        # LINK_LOCAL: 169.254.0.0/16
        if ($b0 -eq 169 -and $b1 -eq 254) {
            return "LINK_LOCAL"
        }

        # DOCUMENTATION: 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24
        if (($b0 -eq 192 -and $b1 -eq 0 -and $b2 -eq 2) -or
            ($b0 -eq 198 -and $b1 -eq 51 -and $b2 -eq 100) -or
            ($b0 -eq 203 -and $b1 -eq 0 -and $b2 -eq 113)) {
            return "DOCUMENTATION"
        }

        # BENCHMARK: 198.18.0.0/15 (198.18.0.0 - 198.19.255.255)
        if ($b0 -eq 198 -and ($b1 -eq 18 -or $b1 -eq 19)) {
            return "BENCHMARK"
        }

        # RESERVED: 240.0.0.0/4, 100.64.0.0/10 (CGNAT), 192.0.0.0/24, 192.88.99.0/24
        if (($b0 -ge 240) -or
            ($b0 -eq 100 -and $b1 -ge 64 -and $b1 -le 127) -or
            ($b0 -eq 192 -and $b1 -eq 0 -and $b2 -eq 0) -or
            ($b0 -eq 192 -and $b1 -eq 88 -and $b2 -eq 99)) {
            return "RESERVED"
        }

        # PRIVATE: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 (RFC 1918)
        if ($b0 -eq 10) {
            return "PRIVATE"
        }
        if ($b0 -eq 172 -and $b1 -ge 16 -and $b1 -le 31) {
            return "PRIVATE"
        }
        if ($b0 -eq 192 -and $b1 -eq 168) {
            return "PRIVATE"
        }

        return "PUBLIC"
    }

    if ($IP.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetworkV6) {
        # IPv6 Loopback: ::1
        if ($IP.Equals([System.Net.IPAddress]::IPv6Loopback)) {
            return "LOOPBACK"
        }
        # IPv6 Unspecified: ::
        if ($IP.Equals([System.Net.IPAddress]::IPv6Any)) {
            return "UNSPECIFIED"
        }
        # IPv6 Multicast: ff00::/8
        if ($bytes[0] -eq 0xff) {
            return "MULTICAST"
        }
        # IPv6 Link-Local: fe80::/10 (fe80-febf)
        if ($bytes[0] -eq 0xfe -and ($bytes[1] -band 0xc0) -eq 0x80) {
            return "LINK_LOCAL"
        }
        # IPv6 Documentation: 2001:db8::/32
        if ($bytes[0] -eq 0x20 -and $bytes[1] -eq 0x01 -and $bytes[2] -eq 0x0d -and $bytes[3] -eq 0xb8) {
            return "DOCUMENTATION"
        }
        # IPv6 Unique Local Address / Private: fc00::/7 (fc00 - fdff, RFC 4193)
        if (($bytes[0] -band 0xfe) -eq 0xfc) {
            return "PRIVATE"
        }

        return "PUBLIC"
    }

    return "UNKNOWN"
}

function Calculate-AzpeAggregateClassification {
    [CmdletBinding()]
    param (
        [string[]]$Classifications
    )

    if ($null -eq $Classifications -or $Classifications.Count -eq 0) {
        return "NONE"
    }

    $hasPrivate = $false
    $hasPublic = $false
    $hasSpecial = $false

    foreach ($c in $Classifications) {
        switch ($c) {
            "PRIVATE" { $hasPrivate = $true }
            "PUBLIC"  { $hasPublic = $true }
            default   { $hasSpecial = $true }
        }
    }

    if ($hasPrivate -and -not $hasPublic -and -not $hasSpecial) {
        return "PRIVATE_ONLY"
    }
    if ($hasPublic -and -not $hasPrivate -and -not $hasSpecial) {
        return "PUBLIC_ONLY"
    }
    if ($hasPrivate -and $hasPublic) {
        return "MIXED_PRIVATE_PUBLIC"
    }
    if ($hasSpecial -and -not $hasPrivate -and -not $hasPublic) {
        return "SPECIAL_ONLY"
    }

    return "MIXED_PRIVATE_PUBLIC"
}

function Resolve-AzpeHost {
    [CmdletBinding()]
    param (
        [string]$Hostname,
        [PSCustomObject]$Capability,
        [int]$TimeoutSeconds = 5
    )

    $sw = [System.Diagnostics.Stopwatch]::StartNew()

    # Check if Hostname is an IP literal
    [System.Net.IPAddress]$literalIp = $null
    if ([System.Net.IPAddress]::TryParse($Hostname.Trim('[', ']'), [ref]$literalIp)) {
        $sw.Stop()
        $cls = Classify-AzpeIpAddress -IP $literalIp
        $ver = if ($literalIp.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetwork) { "IPv4" } else { "IPv6" }
        $aggCls = Calculate-AzpeAggregateClassification -Classifications @($cls)

        $ipObs = [PSCustomObject]@{
            address        = $literalIp.IPAddressToString
            version        = $ver
            classification = $cls
        }

        $dnsObs = [PSCustomObject]@{
            status                  = "NOT_APPLICABLE"
            resolverMode            = "GO_BUILTIN"
            queryHostname           = $Hostname
            durationMs              = $sw.ElapsedMilliseconds
            addresses               = @($ipObs)
            aggregateClassification = $aggCls
            isIpLiteral             = $true
            note                    = "Target is an IP literal. No hostname DNS resolution occurred."
        }

        $addrObs = [PSCustomObject]@{
            classification = $aggCls
            addresses      = @($ipObs)
            privateIps     = if ($cls -eq "PRIVATE") { @($literalIp.IPAddressToString) } else { @() }
            publicIps      = if ($cls -eq "PUBLIC") { @($literalIp.IPAddressToString) } else { @() }
            note           = ""
        }

        return [PSCustomObject]@{
            DNSObservation  = $dnsObs
            AddrObservation = $addrObs
        }
    }

    # Perform DNS resolution
    $rawIpList = [System.Collections.Generic.List[System.Net.IPAddress]]::new()
    $dnsStatus = "SUCCESS"
    $errCategory = ""
    $errMsg = ""

    if ($Capability.HasResolveDnsName) {
        try {
            $dnsRecords = Resolve-DnsName -Name $Hostname -Type A_AAAA -ErrorAction Stop
            foreach ($rec in $dnsRecords) {
                if ($rec.IPAddress) {
                    [System.Net.IPAddress]$parsed = $null
                    if ([System.Net.IPAddress]::TryParse($rec.IPAddress, [ref]$parsed)) {
                        $rawIpList.Add($parsed)
                    }
                }
            }
            if ($rawIpList.Count -eq 0) {
                $dnsStatus = "NOT_FOUND"
                $errCategory = "NOT_FOUND"
                $errMsg = "DNS resolution returned no A or AAAA records for $Hostname"
            }
        } catch {
            $errStr = $_.Exception.Message
            $errMsg = $errStr
            if ($errStr -match 'DNS name does not exist' -or $errStr -match 'not found' -or $errStr -match 'ResourceRecordNotFound') {
                $dnsStatus = "NOT_FOUND"
                $errCategory = "NOT_FOUND"
            } elseif ($errStr -match 'timed out' -or $errStr -match 'timeout') {
                $dnsStatus = "TIMEOUT"
                $errCategory = "TIMEOUT"
            } else {
                $dnsStatus = "FAILURE"
                $errCategory = "GENERIC_ERROR"
            }
        }
    } else {
        # .NET Fallback
        try {
            $addrs = [System.Net.Dns]::GetHostAddresses($Hostname)
            foreach ($a in $addrs) {
                $rawIpList.Add($a)
            }
            if ($rawIpList.Count -eq 0) {
                $dnsStatus = "NOT_FOUND"
                $errCategory = "NOT_FOUND"
                $errMsg = "DNS resolution returned no addresses for $Hostname"
            }
        } catch {
            $errStr = $_.Exception.Message
            $errMsg = $errStr
            if ($errStr -match 'No such host' -or $errStr -match 'not known') {
                $dnsStatus = "NOT_FOUND"
                $errCategory = "NOT_FOUND"
            } else {
                $dnsStatus = "FAILURE"
                $errCategory = "GENERIC_ERROR"
            }
        }
    }

    $sw.Stop()

    if ($dnsStatus -ne "SUCCESS") {
        $dnsObs = [PSCustomObject]@{
            status                  = $dnsStatus
            resolverMode            = "GO_BUILTIN"
            queryHostname           = $Hostname
            durationMs              = $sw.ElapsedMilliseconds
            addresses               = @()
            aggregateClassification = "NONE"
            isIpLiteral             = $false
            errorCategory           = $errCategory
            errorMessage            = $errMsg
            note                    = "DNS resolution failed"
        }
        $addrObs = [PSCustomObject]@{
            classification = "NONE"
            addresses      = @()
            privateIps     = @()
            publicIps      = @()
            note           = "No IP addresses resolved"
        }
        return [PSCustomObject]@{
            DNSObservation  = $dnsObs
            AddrObservation = $addrObs
        }
    }

    # Deduplicate and sort IP addresses deterministically
    $seenMap = [System.Collections.Generic.HashSet[string]]::new()
    $uniqueIpList = [System.Collections.Generic.List[System.Net.IPAddress]]::new()

    foreach ($ip in $rawIpList) {
        $str = $ip.IPAddressToString
        if ($seenMap.Add($str)) {
            $uniqueIpList.Add($ip)
        }
    }

    # Sort IP addresses by IP bytes comparison
    $sortedIps = $uniqueIpList | Sort-Object { $_.IPAddressToString }

    $ipObsList = [System.Collections.Generic.List[PSCustomObject]]::new()
    $classList = [System.Collections.Generic.List[string]]::new()
    $privIps = [System.Collections.Generic.List[string]]::new()
    $pubIps = [System.Collections.Generic.List[string]]::new()

    foreach ($ip in $sortedIps) {
        $cls = Classify-AzpeIpAddress -IP $ip
        $ver = if ($ip.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetwork) { "IPv4" } else { "IPv6" }
        $ipStr = $ip.IPAddressToString

        $classList.Add($cls)
        $ipObsList.Add([PSCustomObject]@{
            address        = $ipStr
            version        = $ver
            classification = $cls
        })

        if ($cls -eq "PRIVATE") {
            $privIps.Add($ipStr)
        } elseif ($cls -eq "PUBLIC") {
            $pubIps.Add($ipStr)
        }
    }

    $aggClass = Calculate-AzpeAggregateClassification -Classifications $classList.ToArray()

    $dnsObs = [PSCustomObject]@{
        status                  = "SUCCESS"
        resolverMode            = "GO_BUILTIN"
        queryHostname           = $Hostname
        durationMs              = $sw.ElapsedMilliseconds
        addresses               = $ipObsList.ToArray()
        aggregateClassification = $aggClass
        isIpLiteral             = $false
    }

    $addrObs = [PSCustomObject]@{
        classification = $aggClass
        addresses      = $ipObsList.ToArray()
        privateIps     = $privIps.ToArray()
        publicIps      = $pubIps.ToArray()
    }

    return [PSCustomObject]@{
        DNSObservation  = $dnsObs
        AddrObservation = $addrObs
    }
}

# --- End Dns.ps1 ---

# --- Begin Output.ps1 ---
# Private/Output.ps1
# Terminal rendering and JSON output formatting for AZPE PowerShell Client

# Set-StrictMode

function Format-AzpeHumanOutput {
    [CmdletBinding()]
    param (
        [PSCustomObject]$Target,
        [PSCustomObject]$Evaluation,
        [switch]$Detailed
    )

    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine("AZPE")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine($Evaluation.Title)
    [void]$sb.AppendLine()
    [void]$sb.AppendLine($Evaluation.Summary)

    if ($Detailed) {
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("--- DETAILED OBSERVATIONS ---")
        [void]$sb.AppendLine("Target FQDN:          $($Target.Hostname)")
        [void]$sb.AppendLine("Target Port:          $($Target.Port)")
        [void]$sb.AppendLine("Target Type:          $($Target.TargetType)")
        [void]$sb.AppendLine("Azure Service Family: $($Target.AzureServiceFamily)")
        [void]$sb.AppendLine("Engine Name:          POWERSHELL_COMPAT")
        [void]$sb.AppendLine("Engine Version:       0.2.0-rc.1")
        [void]$sb.AppendLine("Language Mode:        $($ExecutionContext.SessionState.LanguageMode)")
    }

    return $sb.ToString()
}

function Format-AzpeJsonOutput {
    [CmdletBinding()]
    param (
        [PSCustomObject]$Target,
        [PSCustomObject]$Capability,
        [PSCustomObject]$DNSObs,
        [PSCustomObject]$AddrObs,
        [PSCustomObject]$TCPObs,
        [PSCustomObject]$TLSObs,
        [PSCustomObject]$HTTPObs,
        [PSCustomObject]$Evaluation,
        [int]$DurationMs = 0
    )

    # Force array wrapping for PowerShell single-element array collapsing
    $dnsAddresses = if ($DNSObs -and $DNSObs.addresses) { @($DNSObs.addresses) } else { @() }
    $addrAddresses = if ($AddrObs -and $AddrObs.addresses) { @($AddrObs.addresses) } else { @() }
    $privIps = if ($AddrObs -and $AddrObs.privateIps) { @($AddrObs.privateIps) } else { @() }
    $pubIps = if ($AddrObs -and $AddrObs.publicIps) { @($AddrObs.publicIps) } else { @() }
    $tcpResults = if ($TCPObs -and $TCPObs.results) { @($TCPObs.results) } else { @() }
    $tlsResults = if ($TLSObs -and $TLSObs.results) { @($TLSObs.results) } else { @() }
    $httpResults = if ($HTTPObs -and $HTTPObs.results) { @($HTTPObs.results) } else { @() }
    $warnings = if ($Evaluation -and $Evaluation.Warnings) { @($Evaluation.Warnings) } else { @() }
    $errors = @()

    $osVer = [System.Environment]::OSVersion.VersionString
    $arch = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()

    $jsonObj = [ordered]@{
        schemaVersion = 1
        toolVersion   = "0.1.0"
        timestamp     = [System.DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ")
        durationMs    = $DurationMs
        engine        = [ordered]@{
            name              = "POWERSHELL_COMPAT"
            version           = "0.1.0"
            powerShellVersion = $Capability.PowerShellVersion
            powerShellEdition = $Capability.PowerShellEdition
            languageMode      = $Capability.LanguageMode
        }
        target        = [ordered]@{
            originalInput      = $Target.OriginalInput
            scheme             = $Target.Scheme
            hostname           = $Target.Hostname
            port               = $Target.Port
            requestPath        = $Target.RequestPath
            targetType         = $Target.TargetType
            azureServiceFamily = $Target.AzureServiceFamily
        }
        environment   = [ordered]@{
            os          = $osVer
            architecture = $arch
            hostName    = [System.Environment]::MachineName
            isContainer = $false
            userScope   = if ([System.Environment]::UserName) { $System.Environment.UserName } else { "user" }
        }
        dns           = [ordered]@{
            status                  = if ($DNSObs) { $DNSObs.status } else { "NOT_ATTEMPTED" }
            resolverMode            = "GO_BUILTIN"
            queryHostname           = $Target.Hostname
            durationMs              = if ($DNSObs) { $DNSObs.durationMs } else { 0 }
            addresses               = $dnsAddresses
            aggregateClassification = if ($DNSObs) { $DNSObs.aggregateClassification } else { "NONE" }
            isIpLiteral             = if ($DNSObs) { $DNSObs.isIpLiteral } else { $false }
        }
        address       = [ordered]@{
            classification = if ($AddrObs) { $AddrObs.classification } else { "NONE" }
            addresses      = $addrAddresses
            privateIps     = $privIps
            publicIps      = $pubIps
        }
        tcp           = [ordered]@{
            status          = if ($TCPObs) { $TCPObs.status } else { "NOT_ATTEMPTED" }
            aggregateStatus = if ($TCPObs) { $TCPObs.aggregateStatus } else { "NOT_ATTEMPTED" }
            port            = $Target.Port
            durationMs      = if ($TCPObs) { $TCPObs.durationMs } else { 0 }
            results         = $tcpResults
        }
        tls           = [ordered]@{
            status          = if ($TLSObs) { $TLSObs.status } else { "NOT_ATTEMPTED" }
            aggregateStatus = if ($TLSObs) { $TLSObs.aggregateStatus } else { "NOT_ATTEMPTED" }
            serverName      = $Target.Hostname
            durationMs      = if ($TLSObs) { $TLSObs.durationMs } else { 0 }
            results         = $tlsResults
        }
        http          = [ordered]@{
            status          = if ($HTTPObs) { $HTTPObs.status } else { "NOT_ATTEMPTED" }
            aggregateStatus = if ($HTTPObs) { $HTTPObs.aggregateStatus } else { "NOT_ATTEMPTED" }
            method          = "GET"
            path            = $Target.RequestPath
            durationMs      = if ($HTTPObs) { $HTTPObs.durationMs } else { 0 }
            results         = $httpResults
        }
        assessment    = [ordered]@{
            scenario    = $Evaluation.Scenario
            exitCode    = $Evaluation.ExitCode
            title       = $Evaluation.Title
            explanation = $Evaluation.Explanation
            impact      = $Evaluation.Impact
            summary     = $Evaluation.Summary
            state       = $Evaluation.State
            likelyOwner = $Evaluation.LikelyOwner
            nextAction  = $Evaluation.NextAction
        }
        errors        = $errors
        warnings      = $warnings
    }

    return (ConvertTo-Json $jsonObj -Depth 10)
}

# --- End Output.ps1 ---

# --- Begin Security.ps1 ---
# Private/Security.ps1
# Input sanitization, query value redaction, and string safety helpers for AZPE PowerShell Client

# Set-StrictMode

function Redact-AzpeQueryValues {
    [CmdletBinding()]
    param (
        [string]$PathAndQuery
    )

    if ([string]::IsNullOrEmpty($PathAndQuery)) {
        return ""
    }

    $qIdx = $PathAndQuery.IndexOf('?')
    if ($qIdx -lt 0) {
        return $PathAndQuery
    }

    $basePath = $PathAndQuery.Substring(0, $qIdx)
    $queryStr = $PathAndQuery.Substring($qIdx + 1)
    if ([string]::IsNullOrEmpty($queryStr)) {
        return $PathAndQuery
    }

    $fragment = ""
    $fragIdx = $queryStr.IndexOf('#')
    if ($fragIdx -ge 0) {
        $fragment = $queryStr.Substring($fragIdx)
        $queryStr = $queryStr.Substring(0, $fragIdx)
    }

    $pairs = $queryStr.Split('&')
    $redactedPairs = [System.Collections.Generic.List[string]]::new()

    foreach ($pair in $pairs) {
        if ([string]::IsNullOrEmpty($pair)) {
            continue
        }
        $eqIdx = $pair.IndexOf('=')
        if ($eqIdx -ge 0) {
            $key = $pair.Substring(0, $eqIdx)
            $redactedPairs.Add("$key=REDACTED")
        } else {
            $redactedPairs.Add($pair)
        }
    }

    $result = $basePath + "?" + ($redactedPairs -join "&") + $fragment
    return $result
}

function Sanitize-AzpeLocation {
    [CmdletBinding()]
    param (
        [string]$Location
    )

    if ([string]::IsNullOrEmpty($Location)) {
        return ""
    }

    # Strip userinfo (user:pass@) if present in full URL
    $sanitized = $Location
    if ($sanitized -match '^(https?://)([^/@]+@)(.+)$') {
        $sanitized = $Matches[1] + $Matches[3]
    }

    return (Redact-AzpeQueryValues -PathAndQuery $sanitized)
}

function Test-AzpeSafeInput {
    [CmdletBinding()]
    param (
        [string]$RawInput
    )

    if ([string]::IsNullOrWhiteSpace($RawInput)) {
        throw "missing target"
    }

    # Reject control characters (CR, LF, NUL, TAB, etc.)
    foreach ($char in $RawInput.ToCharArray()) {
        if ([char]::IsControl($char)) {
            throw "target contains invalid control characters"
        }
    }

    # Reject URLs with embedded credentials (e.g. https://user:pass@host)
    if ($RawInput -match '://[^/]*@') {
        throw "URLs containing embedded credentials are not allowed"
    }
}

# --- End Security.ps1 ---

# --- Begin Tcp.ps1 ---
# Private/Tcp.ps1
# Direct TCP connectivity probing for captured IP addresses for AZPE PowerShell Client

# Set-StrictMode

function Test-AzpeTcpConnectivity {
    [CmdletBinding()]
    param (
        [string]$Hostname,
        [int]$Port = 443,
        [string[]]$PrivateIPs,
        [PSCustomObject]$Capability,
        [int]$TimeoutSeconds = 5
    )

    if ($null -eq $PrivateIPs -or $PrivateIPs.Count -eq 0) {
        return [PSCustomObject]@{
            status          = "SKIPPED"
            aggregateStatus = "NOT_ATTEMPTED"
            port            = $Port
            durationMs      = 0
            results         = @()
            note            = "TCP connectivity probe not performed"
        }
    }

    $swTotal = [System.Diagnostics.Stopwatch]::StartNew()
    $results = [System.Collections.Generic.List[PSCustomObject]]::new()

    $connectedCount = 0
    $failedCount = 0

    foreach ($ip in $PrivateIPs) {
        # Format destination (IPv6 uses bracketed notation with port)
        $dest = if ($ip.Contains(':')) { "[$ip]:$Port" } else { "$ip`:$Port" }
        $swIp = [System.Diagnostics.Stopwatch]::StartNew()

        $isSuccess = $false
        $errCat = ""
        $errMsg = ""
        $statusStr = "ERROR"

        if ($Capability.HasTestNetConnection) {
            try {
                $tnc = Test-NetConnection -ComputerName $ip -Port $Port -InformationLevel Detailed -WarningAction SilentlyContinue
                if ($tnc -and $tnc.TcpTestSucceeded) {
                    $isSuccess = $true
                    $statusStr = "CONNECTED"
                } else {
                    $statusStr = "TIMED_OUT"
                    $errCat = "TIMEOUT"
                    $errMsg = "TCP connection to $dest timed out"
                }
            } catch {
                $statusStr = "CONNECTION_REFUSED"
                $errCat = "CONNECTION_REFUSED"
                $errMsg = $_.Exception.Message
            }
        } else {
            # Sockets TcpClient fallback
            try {
                $client = [System.Net.Sockets.TcpClient]::new()
                $asyncResult = $client.BeginConnect($ip, $Port, $null, $null)
                $waitResult = $asyncResult.AsyncWaitHandle.WaitOne([timespan]::FromSeconds($TimeoutSeconds), $false)

                if ($waitResult -and $client.Connected) {
                    $client.EndConnect($asyncResult)
                    $isSuccess = $true
                    $statusStr = "CONNECTED"
                } else {
                    $statusStr = "TIMED_OUT"
                    $errCat = "TIMEOUT"
                    $errMsg = "TCP connection to $dest timed out"
                }
                $client.Close()
            } catch {
                $errStr = $_.Exception.Message
                if ($errStr -match 'refused') {
                    $statusStr = "CONNECTION_REFUSED"
                    $errCategory = "CONNECTION_REFUSED"
                } elseif ($errStr -match 'unreachable') {
                    $statusStr = "UNREACHABLE"
                    $errCategory = "UNREACHABLE"
                } else {
                    $statusStr = "ERROR"
                    $errCategory = "GENERIC_ERROR"
                }
                $errMsg = $errStr
            }
        }

        $swIp.Stop()

        if ($isSuccess) {
            $connectedCount++
        } else {
            $failedCount++
        }

        $results.Add([PSCustomObject]@{
            address       = $ip
            destination   = $dest
            port          = $Port
            status        = $statusStr
            durationMs    = $swIp.ElapsedMilliseconds
            errorCategory = $errCat
            errorMessage  = $errMsg
        })
    }

    $swTotal.Stop()

    $aggStatus = "NONE_CONNECTED"
    $topStatus = "FAILED"

    if ($connectedCount -eq $PrivateIPs.Count) {
        $aggStatus = "ALL_CONNECTED"
        $topStatus = "SUCCESS"
    } elseif ($connectedCount -gt 0 -and $failedCount -gt 0) {
        $aggStatus = "PARTIALLY_CONNECTED"
        $topStatus = "PARTIAL"
    }

    return [PSCustomObject]@{
        status          = $topStatus
        aggregateStatus = $aggStatus
        port            = $Port
        durationMs      = $swTotal.ElapsedMilliseconds
        results         = $results.ToArray()
    }
}

# --- End Tcp.ps1 ---

# --- Begin Invoke-AzpeProbe.ps1 ---
# Public/Invoke-AzpeProbe.ps1
# Primary cmdlet for AZPE PowerShell Compatibility Client

<#
.SYNOPSIS
    Diagnoses Azure Private Endpoint connectivity directly from Windows workloads.

.DESCRIPTION
    Invoke-AzpeProbe is the official PowerShell compatibility client for AZPE.
    It combines DNS resolution, IP classification, TCP connectivity probing,
    TLS validation, and minimal unauthenticated HTTPS health probing into a
    single plain-language diagnostic assessment.

    Designed for restricted Windows and Azure Virtual Desktop environments where
    arbitrary native binary EXEs cannot easily be executed.

    This client operates strictly within enterprise security controls (AppLocker,
    WDAC, Execution Policies, Constrained Language Mode). It does NOT alter or
    bypass any security policy.

.PARAMETER Target
    The Azure service hostname or URL to diagnose (e.g. myvault.vault.azure.net).

.PARAMETER TimeoutSeconds
    Operation deadline timeout in seconds (default: 5).

.PARAMETER Detailed
    Produces multi-section detailed terminal diagnostic output.

.PARAMETER Json
    Outputs machine-readable JSON (schemaVersion: 1) to stdout.

.PARAMETER NoHttp
    Skips the minimal HTTP probe phase and returns Phase 4 TLS results.

.PARAMETER NoColor
    Disables colorized terminal output.

.EXAMPLE
    Invoke-AzpeProbe myvault.vault.azure.net

.EXAMPLE
    Invoke-AzpeProbe -Target https://myvault.vault.azure.net/ -Detailed

.EXAMPLE
    Invoke-AzpeProbe myvault.vault.azure.net -Json

.NOTES
    No Azure login or credentials required.
    Run directly inside the affected workload environment.
#>

# Set-StrictMode

function Invoke-AzpeProbe {
    [CmdletBinding()]
    [Alias("azpe")]
    param (
        [Parameter(Position = 0, Mandatory = $false, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
        [string]$Target = "",

        [Parameter(Mandatory = $false)]
        [int]$TimeoutSeconds = 5,

        [Parameter(Mandatory = $false)]
        [switch]$Detailed,

        [Parameter(Mandatory = $false)]
        [switch]$Json,

        [Parameter(Mandatory = $false)]
        [switch]$NoHttp,

        [Parameter(Mandatory = $false)]
        [switch]$NoColor
    )

    $swTotal = [System.Diagnostics.Stopwatch]::StartNew()

    if ([string]::IsNullOrWhiteSpace($Target)) {
        $errEval = [PSCustomObject]@{
            Scenario    = "INVALID_INPUT"
            ExitCode    = 2
            Title       = "Target required"
            Explanation = "No Azure service hostname or URL was specified."
            Impact      = "AZPE requires a target Azure service hostname to diagnose."
            Summary     = "Usage:`n  .\Invoke-AzpeProbe.ps1 <target-hostname-or-url>`n  Invoke-AzpeProbe myvault.vault.azure.net`n`nExample:`n  .\Invoke-AzpeProbe.ps1 sapintegrationsde.blob.core.windows.net"
            State       = "UNKNOWN"
            LikelyOwner = "UNKNOWN"
            NextAction  = "Provide the target Azure service hostname configured in your application."
            Warnings    = @()
        }
        if ($Json) {
            $cap = Get-AzpeCapability
            $dummyTgt = [PSCustomObject]@{ OriginalInput = ""; Scheme = "https"; Hostname = ""; Port = 443; RequestPath = "/"; TargetType = "UNRECOGNIZED_TARGET"; AzureServiceFamily = "NONE" }
            Format-AzpeJsonOutput -Target $dummyTgt -Capability $cap -Evaluation $errEval
        } else {
            Write-Output "AZPE`n`nThe target Azure service hostname or URL is required.`n`nUsage:`n  .\Invoke-AzpeProbe.ps1 <target-hostname-or-url>`n  Invoke-AzpeProbe myvault.vault.azure.net`n`nExample:`n  .\Invoke-AzpeProbe.ps1 sapintegrationsde.blob.core.windows.net"
        }
        return $errEval
    }

    # 1. Safety & Parameter Parsing
    try {
        Test-AzpeSafeInput -RawInput $Target
    } catch {
        $errEval = [PSCustomObject]@{
            Scenario    = "INVALID_INPUT"
            ExitCode    = 2
            Title       = "Invalid target"
            Explanation = $_.Exception.Message
            Impact      = "AZPE could not parse the requested target."
            Summary     = $_.Exception.Message
            State       = "UNKNOWN"
            LikelyOwner = "UNKNOWN"
            NextAction  = "Provide a valid Azure service hostname or URL."
            Warnings    = @()
        }
        if ($Json) {
            $cap = Get-AzpeCapability
            $dummyTgt = [PSCustomObject]@{ OriginalInput = $Target; Scheme = "https"; Hostname = $Target; Port = 443; RequestPath = "/"; TargetType = "UNRECOGNIZED_TARGET"; AzureServiceFamily = "NONE" }
            Write-Host (Format-AzpeJsonOutput -Target $dummyTgt -Capability $cap -Evaluation $errEval)
        } else {
            Write-Host "AZPE`n`nInvalid target: $($_.Exception.Message)"
        }
        return $errEval
    }

    # 2. Parse & Normalize Target
    $parsedTgt = Parse-AzpeTarget -RawInput $Target
    $cap = Get-AzpeCapability

    # If IP literal or unrecognized non-Azure target, evaluate directly
    if ($parsedTgt.TargetType -in @("IP_LITERAL", "UNRECOGNIZED_TARGET", "POSSIBLE_AZURE_SERVICE")) {
        $eval = Get-AzpeEvaluation -Target $parsedTgt -DNSObs $null -AddrObs $null -TCPObs $null -TLSObs $null -HTTPObs $null
        $swTotal.Stop()

        if ($Json) {
            Write-Host (Format-AzpeJsonOutput -Target $parsedTgt -Capability $cap -Evaluation $eval -DurationMs $swTotal.ElapsedMilliseconds)
        } else {
            Write-Host (Format-AzpeHumanOutput -Target $parsedTgt -Evaluation $eval -Detailed:$Detailed)
        }

        return $eval
    }

    # 3. Phase 1 & 2: DNS Resolution & Address Classification
    $dnsResult = Resolve-AzpeHost -Hostname $parsedTgt.Hostname -Capability $cap -TimeoutSeconds $TimeoutSeconds
    $dnsObs = $dnsResult.DNSObservation
    $addrObs = $dnsResult.AddrObservation

    if ($dnsObs.status -ne "SUCCESS" -or $addrObs.classification -ne "PRIVATE_ONLY") {
        $eval = Get-AzpeEvaluation -Target $parsedTgt -DNSObs $dnsObs -AddrObs $addrObs -TCPObs $null -TLSObs $null -HTTPObs $null
        $swTotal.Stop()

        if ($Json) {
            Write-Host (Format-AzpeJsonOutput -Target $parsedTgt -Capability $cap -DNSObs $dnsObs -AddrObs $addrObs -Evaluation $eval -DurationMs $swTotal.ElapsedMilliseconds)
        } else {
            Write-Host (Format-AzpeHumanOutput -Target $parsedTgt -Evaluation $eval -Detailed:$Detailed)
        }

        return $eval
    }

    # 4. Phase 3: Direct TCP Connectivity Probing
    $tcpObs = Test-AzpeTcpConnectivity -Hostname $parsedTgt.Hostname -Port $parsedTgt.Port -PrivateIPs $addrObs.privateIps -Capability $cap -TimeoutSeconds $TimeoutSeconds

    if ($tcpObs.aggregateStatus -ne "ALL_CONNECTED") {
        $eval = Get-AzpeEvaluation -Target $parsedTgt -DNSObs $dnsObs -AddrObs $addrObs -TCPObs $tcpObs -TLSObs $null -HTTPObs $null
        $swTotal.Stop()

        if ($Json) {
            Write-Host (Format-AzpeJsonOutput -Target $parsedTgt -Capability $cap -DNSObs $dnsObs -AddrObs $addrObs -TCPObs $tcpObs -Evaluation $eval -DurationMs $swTotal.ElapsedMilliseconds)
        } else {
            Write-Host (Format-AzpeHumanOutput -Target $parsedTgt -Evaluation $eval -Detailed:$Detailed)
        }

        return $eval
    }

    # 5. Phase 4 & 5: TLS & HTTPS Probing
    $connectedIps = @()
    foreach ($r in $tcpObs.results) {
        if ($r.status -eq "CONNECTED") {
            $connectedIps += $r.address
        }
    }

    $probeResult = Invoke-AzpeCurlHttpsProbe -Hostname $parsedTgt.Hostname -Port $parsedTgt.Port -Scheme $parsedTgt.Scheme -PathAndQuery $parsedTgt.RequestPath -ConnectedIPs $connectedIps -Capability $cap -TimeoutSeconds $TimeoutSeconds -NoHttp:$NoHttp
    $tlsObs = $probeResult.TLSObservation
    $httpObs = $probeResult.HTTPObservation

    # 6. Evaluation Decision Engine
    $eval = Get-AzpeEvaluation -Target $parsedTgt -DNSObs $dnsObs -AddrObs $addrObs -TCPObs $tcpObs -TLSObs $tlsObs -HTTPObs $httpObs -NoHttp:$NoHttp
    $swTotal.Stop()

    # 7. Render Output
    $global:LastAzpeResult = $eval
    if ($Json) {
        Write-Host (Format-AzpeJsonOutput -Target $parsedTgt -Capability $cap -DNSObs $dnsObs -AddrObs $addrObs -TCPObs $tcpObs -TLSObs $tlsObs -HTTPObs $httpObs -Evaluation $eval -DurationMs $swTotal.ElapsedMilliseconds)
    } else {
        Write-Host (Format-AzpeHumanOutput -Target $parsedTgt -Evaluation $eval -Detailed:$Detailed)
    }

    return $eval
}

function Parse-AzpeTarget {
    [CmdletBinding()]
    param (
        [string]$RawInput
    )

    $trimmed = $RawInput.Trim()

    $hasScheme = $trimmed.Contains("://")
    $scheme = "https"
    $rawToParse = $trimmed

    if ($hasScheme) {
        $schemeEnd = $trimmed.IndexOf("://")
        $scheme = $trimmed.Substring(0, $schemeEnd).ToLower()
        if ($scheme -ne "http" -and $scheme -ne "https") {
            throw "unsupported scheme '$scheme' (only http and https are supported)"
        }
    } else {
        $rawToParse = "https://$trimmed"
    }

    $uri = [System.Uri]::new($rawToParse)

    if (-not [string]::IsNullOrEmpty($uri.UserInfo)) {
        throw "URLs containing embedded credentials are not allowed"
    }

    $hostname = $uri.DnsSafeHost
    if ([string]::IsNullOrEmpty($hostname)) {
        $hostname = $uri.Host
    }

    $hostname = $hostname.Trim('[', ']')
    if ([string]::IsNullOrEmpty($hostname)) {
        throw "missing hostname in target"
    }

    $port = $uri.Port
    if ($port -le 0) {
        $port = if ($scheme -eq "http") { 80 } else { 443 }
    }

    $requestPath = $uri.PathAndQuery
    if ([string]::IsNullOrEmpty($requestPath)) {
        $requestPath = "/"
    }

    $cls = Classify-AzpeTarget -Hostname $hostname

    return [PSCustomObject]@{
        OriginalInput      = $trimmed
        Scheme             = $scheme
        Hostname           = $hostname
        Port               = $port
        RequestPath        = $requestPath
        TargetType         = $cls.TargetType
        AzureServiceFamily = $cls.AzureServiceFamily
    }
}

# --- End Invoke-AzpeProbe.ps1 ---

# Execution Router for Standalone Script
if ($MyInvocation.InvocationName -ne '.') {
    $evalResult = Invoke-AzpeProbe -Target $Target -TimeoutSeconds $TimeoutSeconds -Detailed:$Detailed -Json:$Json -NoHttp:$NoHttp -NoColor:$NoColor
    if ($evalResult -and $evalResult.ExitCode -ne $null) {
        $host.SetShouldExit($evalResult.ExitCode)
        [System.Environment]::ExitCode = $evalResult.ExitCode
    }
}
